/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ty_android_ndkdevdemo_NdkLib */

#ifndef _Included_com_ty_android_ndkdevdemo_NdkLib
#define _Included_com_ty_android_ndkdevdemo_NdkLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ty_android_ndkdevdemo_NdkLib
 * Method:    getData
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ty_android_ndkdevdemo_NdkLib_getData
  (JNIEnv *, jobject);

/*
 * Class:     com_ty_android_ndkdevdemo_NdkLib
 * Method:    updateData
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ty_android_ndkdevdemo_NdkLib_updateData
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
